# Generated by Django 3.2.3 on 2021-10-22 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websiteName', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=50)),
                ('passworduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authUser.passworduser')),
            ],
        ),
    ]
